### ISSUE TITLE
Your First Issue!

### ISSUE THREAD

**Issue by camchardukian** [lucilapastore/HackerRank-s-Solutions#1]
Hey Lucila,

I saw you were doing the HackerRank challenges and uploading your solutions here. That's great! If you need help with any of them and would like me to make a video tutorial or pair program together, let me know!

Cheers,

Cam

**Comment by lucilapastore** [comment]
Cam thank you so much. Your repo is very helpfull indeed. Is there any chance we can solve them together via video call? Let me know what time is better for you please! That would be a huge help!

Best,

Lu!

**Comment by camchardukian** [comment]
No worries, glad to help. Let me check my schedule for the next week or so, and then I'll contact you via the Whatsapp number you sent to me. Cheers!
